site_name: QuiraData
site_url: https://quiradata.com
copyright: Copyright &copy; 2024 Andres Delgadillo, PhD
#repo_url: https://github.com/ardelgadillov/sudoku
#repo_name: ardelgadillov


nav:
    -   Home: index.md
    -   Optimization:
            - optimization/index.md
            -   Sudoku Solver: optimization/sudoku.md
            -   Project2: optimization/notebooks.ipynb
    -   Machine Learning:
            - machine_learning/index.md
            -   Project1: machine_learning/markdown.md
            -   Project2: machine_learning/notebooks.ipynb
            -   Linear Regression: machine_learning/Supervised_Learning_Regression.ipynb
    -   Blog:
            - blog/index.md
    -   About: about.md

plugins:
    -   mkdocs-jupyter:
            ignore_h1_titles: True
    -   search
    #    -   social
    -   blog:
            authors_file: "blog/.authors.yml"
    -   tags

theme:
    name: material

    custom_dir: docs/overrides

    palette:
        # Palette toggle for light mode
        -   media: "(prefers-color-scheme: light)"
            primary: black
            scheme: default
            toggle:
                icon: material/weather-night
                name: Switch to dark mode

        # Palette toggle for dark mode
        -   media: "(prefers-color-scheme: dark)"
            primary: black
            scheme: slate
            toggle:
                icon: material/weather-sunny
                name: Switch to light mode

    font:
        code: JetBrains Mono

    logo: assets/logo/{quiradata}_light.svg

    favicon: assets/logo/qd.ico

    icon:
        repo: fontawesome/brands/github

    features:
        - navigation.instant
        - navigation.instant.progress
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.indexes
        - search.suggest
        - search.highlight

extra:
    social:
        -   icon: fontawesome/brands/github
            link: https://github.com/ardelgadillov
        -   icon: fontawesome/brands/linkedin
            link: https://www.linkedin.com/in/andresdelgadillo

#extra_javascript:
#     -   overrides/toggle.js
#    -   https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js
#    -   https://fonts.googleapis.com/icon?family=Material+Icons

extra_css:
    -   overrides/styles.css
#    -   https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css



markdown_extensions:
    -   attr_list
    -   md_in_html
    -   pymdownx.blocks.caption
    -   pymdownx.emoji:
            emoji_index: !!python/name:material.extensions.emoji.twemoji
            emoji_generator: !!python/name:material.extensions.emoji.to_svg
