site_name: QuiraData
site_url: https://quiradata.com
site_author: Andres Delgadillo, PhD
site_description: >-
    Quira Data is a consulting company focus on Data Science, Optimization and Machine Learning
    applied to electricity systems

copyright: Copyright &copy; 2024 Andres Delgadillo, PhD
#repo_url: https://github.com/ardelgadillov/sudoku
#repo_name: ardelgadillov


nav:
    -   Home: index.md
    -   Optimization:
            -   optimization/index.md
            -   Sudoku Solver: optimization/sudoku.md
            -   Traveling Salesperson Problem: optimization/travel_sales.ipynb
    -   Machine Learning:
#            - machine_learning/index.md
            -   Project1: machine_learning/markdown.md
            -   Project2: machine_learning/notebooks.ipynb
            -   Linear Regression: machine_learning/Supervised_Learning_Regression.ipynb
    -   Blog:
            - blog/index.md
    -   About: about.md

plugins:
    -   mkdocs-jupyter:
            ignore_h1_titles: True
            toc_depth: 2
    -   search
    #    -   social
    -   blog:
            blog_toc: true
            archive_date_format: MMMM yyyy
            authors_file: "blog/.authors.yml"
    -   tags
#    -   privacy
#    -   enumerate-headings
    -   mkdocs-add-teaser:
            teaser_class: 'teaser'
            add_to_meta: true

theme:
    name: material

    custom_dir: docs/overrides

    palette:
        # Palette toggle for light mode
        -   media: "(prefers-color-scheme: light)"
            primary: white
            scheme: default
            toggle:
                icon: material/weather-night
                name: Switch to dark mode

        # Palette toggle for dark mode
        -   media: "(prefers-color-scheme: dark)"
            primary: black
            scheme: slate
            toggle:
                icon: material/weather-sunny
                name: Switch to light mode

    font:
        text: JetBrains Mono
        code: JetBrains Mono

    logo: assets/logo/{quiradata}_light.svg

    favicon: assets/logo/qd.ico

    icon:
        repo: fontawesome/brands/github

    features:
        - navigation.instant
        - navigation.instant.progress
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.indexes
        - search.suggest
        - search.highlight
        - content.code.copy
        - content.code.select

extra:
    social:
        -   icon: fontawesome/brands/github
            link: https://github.com/ardelgadillov
        -   icon: fontawesome/brands/linkedin
            link: https://www.linkedin.com/in/andresdelgadillo

extra_javascript:
    -   https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js
    -   overrides/katex.js
    -   https://unpkg.com/katex@0/dist/katex.min.js
    -   https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
    -   overrides/styles.css
    -   https://unpkg.com/katex@0/dist/katex.min.css
#    -   https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css

markdown_extensions:
    -   attr_list
    -   md_in_html
    -   pymdownx.blocks.caption
    -   pymdownx.emoji:
            emoji_index: !!python/name:material.extensions.emoji.twemoji
            emoji_generator: !!python/name:material.extensions.emoji.to_svg
    -   pymdownx.highlight:
            anchor_linenums: true
            line_spans: __span
            pygments_lang_class: true
    -   pymdownx.inlinehilite
    -   pymdownx.snippets
    -   pymdownx.superfences
    -   meta
    -   tables
    -   toc:
            toc_depth: 2
            permalink: true
