authors:
    Andres:
        name: Andres Delgadillo, PhD       # Author name
        description: string # Author description
        avatar: url         # Author avatar
        slug: url           # Author profile slug
        url: https://www.linkedin.com/in/andresdelgadillo            # Author website URL