authors:
    Andres:
        name: Andres Delgadillo, PhD       # Author name
        description: Data Scientist  # Author description
        avatar: https://avatars.githubusercontent.com/ardelgadillov         # Author avatar
        url: https://www.linkedin.com/in/andresdelgadillo            # Author website URL